[package]
name = "konane-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "konane_engine"
path = "src/lib/mod.rs"

[[bin]]
name = "konane"
path = "src/bin/konane.rs"

[dependencies]
